from selenium.webdriver.common.by import By


class MainPageLocators:
    ROOT_FIELD = (By.ID, "map")
    INPUT_FROM = (By.XPATH, "//input[@id='from']")
    INPUT_TO = (By.XPATH, "//input[@id='to']")
    POINTS = (By.XPATH, "//ymaps[@class='ymaps-2-1-79-route-pin__label-a']")
    ROUTES_OPTIONS = (By.XPATH, "//ymaps[@class='ymaps-2-1-79-graphics-canvas']/ymaps/canvas")
    CHOOSE_ROUTES_BLOCK = (By.XPATH, "//div[@class='type-picker shown']")
    PRICE_TEXT = (By.XPATH, "//div[@class='results-text']/div[@class='text']")
    DURATION_TEXT = (By.XPATH, "//div[@class='results-text']/div[@class='duration']")
    OPTIMAL_BLOCK = (By.XPATH, "//div[contains(text(), 'Оптимальный')]")
    FAST_BLOCK = (By.XPATH, "//div[contains(text(), 'Быстрый')]")
    SELF_BLOCK = (By.XPATH, "//div[contains(text(), 'Свой')]")
    VEHICLE_TYPES = (By.XPATH, "//div[@class='types-container']/div[@class='type']")
    CALL_TAXI_BTN = (By.XPATH, "//button[contains(text(), 'Вызвать такси')]")
    BOOK_DRIVE_BTN = (By.XPATH, "//button[contains(text(), 'Забронировать')]")
    VEHICLE_TYPES_DRIVE = (By.XPATH, "//div[@class='types-container']/div[@class='type drive']/img")
    TARIFF_PICKER = (By.XPATH, "//div[@class='tariff-picker shown']")
    TARIFF_TYPES = (By.XPATH, "//div[@class='tariff-cards']/div[contains(@class, 'tcard')]")
    TARIFF_TYPE_TITLE = (By.XPATH, ".//div[@class='tcard-title']")
    TARIFF_TYPE_INFO = (By.XPATH, ".//button")
    TARIFF_TYPE_DESCRIPTION = (By.XPATH, "//div[@class='tcard active']/div/div/div[@class='i-dPrefix']")
    TARIFF_TYPE_DESCRIPTION_SHOW = (By.XPATH, "//div[@class='tcard active']/div[contains(@class, 'show')]")
    PHONE = (By.XPATH, "//div[@class='form']/div/div[contains(text(), 'Телефон')]")
    PAYMENT_METHOD = (By.XPATH, "//div[@class='form']/div/div[contains(text(), 'Способ оплаты')]")
    COMMENT = (By.ID, "comment")
    ORDER_REQUIREMENT = (By.XPATH, "//div[@class='form']/div[@class='reqs']")
    TARIFF_TYPE_PRICE = (By.XPATH, ".//div[@class='tcard-price']")
    CHOOSE_LAPTOP = (By.XPATH, "//div[contains(text(), 'Столик для ноутбука')]")
    TAXI_ORDER_BTN = (By.XPATH, "//button[@class='smart-button']")
    ORDER_NUMBER = (By.XPATH, "//div[@class='order-number']")
    TRIP_DETAIL_BTN = (By.XPATH, "//img[@alt='burger']//parent::button")
    FINAl_PRICE = (By.XPATH, "//div[@class='order-details-content']/div[contains(text(), 'Стоимость')]")
    CANCEL_TRIP_BTN = (By.XPATH, "//img[@alt='close']//parent::button")